config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  devise_for :users
  resources :users
  resources :posts

  get 'pages/about'
  get 'pages/competition'
  get 'pages/blog'

  get 'admin', to: 'admin#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if current_user.admin?
      can :manage, :all
    else
      can :read, :post
      can :read, :page
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category

  include Mongoid::Document
  include Mongoid::Timestamps

  field :name,   type: String
  
  has_and_belongs_to_many :posts

end

app/models/post.rb
require 'elasticsearch/model'

class Post

  include Mongoid::Document
  include Mongoid::Timestamps
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include Elasticsearch::Model::Serializing

  field :title,   type: String
  field :lead,    type: String
  field :body,    type: String

  has_and_belongs_to_many :categories
  belongs_to :user

  def as_indexed_json(options={})
    as_json(except: [:id, :_id])
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  ## Personal Details
  field :first_name
  field :last_name

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Admin
  field :admin,              type: Boolean, default: false
  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  #

  has_many :posts

  # Hack for fixing mongoid, devise and rails 4.1 incompatibility
  class << self
    def serialize_from_session(key, salt)
      record = to_adapter.get(key[0]['$oid'])
      record if record && record.authenticatable_salt == salt
    end
  end

  def admin?
    self.admin
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!

  layout 'admin'

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

  def competition

  end

  def blog

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  respond_to :json, :html

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = if params[:q]
               Post.search(params[:q]).records
             else
               Post.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
             end
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:q)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  respond_to :json

  def index
    @users = User.all
    render 'index.rabl'
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.haml
-flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{['notice', 'success'].include?(name) ? "success" : "danger"}"}
      %a.close{data: {dismiss: 'alert'}} ×
      =content_tag :div, msg, id: "flash_#{name}"
  - if msg.is_a?(Array)
    %div.alert{class: "alert-#{[:notice, :success].include?(name) ? "success" : "danger"}"}
      %a.close{data: {dismiss: 'alert'}} ×
      - msg.each do |m|
        =content_tag :div, m

app/views/layouts/_footer.html.haml
%footer
  &copy; Website Name

app/views/layouts/_login_banner.html.haml
.banner
  %h3.strong.text-center Banner title
  .text-center
    =image_tag 'fork_knife.png'
  .text-justify
    %p Marketing message comes here...
  %form.email-form
    .row.nopadding
      .col-xs-10.nopadding
        %input{type: 'email', placeholder: 'Enter your email...'}
      .col-xs-2.nopadding
        %button
          %i.fa.fa-angle-right.fa-2x

app/views/layouts/_logout_banner.html.haml
.banner
  %h3.strong.text-center Banner title
  .text-center
    =image_tag 'fork_knife.png'
  .text-justify
    %p
  %form.email-form
    .row.nopadding
      .col-xs-10.nopadding
        %input{type: 'email', placeholder: 'Enter your email...'}
      .col-xs-2.nopadding
        %button
          %i.fa.fa-angle-right.fa-2x

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{type: 'button', data: {toggle: 'collapse', target: '#main-menu'}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar


    .collapse.navbar-collapse#main-menu
      %ul.menu-link.nav.navbar-nav
        %li{class: ('active' if current_page?(root_url))}
          =link_to 'Home', root_path
        %li{class: ('active' if current_page?(pages_about_url))}
          =link_to 'About', pages_about_path
        %li{class: ('active' if current_page?(pages_blog_url))}
          =link_to 'Blog', pages_blog_path
        %li{class: ('active' if current_page?(pages_competition_url))}
          =link_to 'Competition', pages_competition_path
        %li{class: ('active' if devise_controller?)}
          - if user_signed_in?
            = link_to 'Logout', destroy_user_session_path, method: :delete
          - else
            = link_to 'Login', new_user_session_path
        - if current_user.try(:admin?)
          %li{class: ('active' if current_page?(admin_url))}
            = link_to 'Admin', admin_path, data: {'no_turbolink' => ''}
      %ul.nav.navbar-nav.navbar-right.social-icons
        %li
          %a{href: "#"}
            %span.fa-stack.fa-lg
              %i.fa.fa-circle.fa-stack-2x
              %i.fa.fa-twitter.fa-stack-1x.fa-inverse
        %li
          %a{href: "#"}
            %span.fa-stack.fa-lg
              %i.fa.fa-circle.fa-stack-2x
              %i.fa.fa-facebook.fa-stack-1x.fa-inverse
        %li
          %a{href: "#"}
            %span.fa-stack.fa-lg
              %i.fa.fa-circle.fa-stack-2x
              %i.fa.fa-google-plus.fa-stack-1x.fa-inverse
        %li
          %a{href: "#"}
            %span.fa-stack.fa-lg
              %i.fa.fa-circle.fa-stack-2x
              %i.fa.fa-pinterest.fa-stack-1x.fa-inverse
        %li
          %a{href: "#"}
            %span.fa-stack.fa-lg
              %i.fa.fa-circle.fa-stack-2x
              %i.fa.fa-instagram.fa-stack-1x.fa-inverse

app/views/layouts/_sidebar.html.haml
.sidebar
  #logo-widget.hidden-xs.hidden-sm
    = link_to root_path do
      .logo
        =image_tag 'logo.png'
      .brand
        =image_tag 'brand.png'
      .tagline.text-center
        %em This is the tagline
  - unless devise_controller?
    .divider
    #banner-widget
      - if current_user
        =render 'layouts/login_banner'
      - else
        =render 'layouts/logout_banner'

      .divider
    #tweets-widget
      %h3.strong Tweets
      - 5.times do
        %p
          @
          %strong 'username'
          Content...
          =link_to 'something', '#'

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title App
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'ember-application'
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .container
      #ember-app

    =render 'layouts/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title App
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .container
      = render 'layouts/flash'
      .row
        .col-md-3
          = render 'layouts/sidebar'
        .col-md-9
          = yield
      = render 'layouts/footer'

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title App
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .container
      = render 'layouts/flash'
      .row
        .col-md-3
          = render 'layouts/sidebar'
        .col-md-9
          .entry
            .well
              = yield
      = render 'layouts/footer'

app/views/pages/about.html.haml
%h1 About

app/views/pages/blog.html.haml
%h1 Blog

app/views/pages/competition.html.haml
%h1 Competition

app/views/posts/_post.html.haml
.entry
  %article#post-id
    %header
      .entry-date
        %time.entry-date{datetime:'2014-02-02'}=post.updated_at
      =link_to post do
        %h3=post.title
    =image_tag 'content_image.jpg', class: 'img-responsive'
    .entry-summary
      %p=post.lead
      .meta-nav
    %footer
      .categories
        =post.categories.map(&:name).join(', ')
      .more-link.pull-right
        =link_to 'Read Full Article', post

app/views/posts/index.html.haml
= form_tag 'posts', url: posts_path, method: :get do
  = label_tag :search
  = text_field_tag :q
  = submit_tag :search

= render @posts

= will_paginate @posts

app/views/posts/show.html.haml
.entry
  %article#post-id
    %header
      .entry-date
        %time.entry-date{datetime:'2014-02-02'}=@post.updated_at
      =link_to @post do
        %h3=@post.title
    =image_tag 'content_image.jpg', class: 'img-responsive'
    .entry-summary
      %p=@post.lead
      .meta-nav
    %section
      %p=@post.body